[package]
name = "pet"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
miette = { version = "7.2.0", features = ["fancy"] }
owo-colors = "4.0.0"
pest = "2.7.10"
pest_derive = "2.7.10"
rustyline = { version = "14.0.0", features = ["derive"] }
